defaults:
  - task: adroit_hammer

name: train_dp3

task_name: ${task.name}
shape_meta: ${task.shape_meta}

exp_name: "debug"

horizon: 5
n_obs_steps: 2
n_action_steps: 4
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True
use_action_embed: True
use_conv_action_embed: False
conv_hidden_dims: [128, 256]
conv_latent_cz: 32
conv_kernel_size: 5
conv_n_groups: 8
action_recon_beta: 0.5
no_pre_action: True
ft_all_actions: True
eval: False
offline: False
online: False
num_inference_steps: 10
cm_inference_steps: 1
feature_type: '2D' # 2D, 3D, or 2D3D
use_agent_pos: true
use_pretrained_2DEncoder: False
clip_std_min: 0.0067
clip_std_max: null
action_norm: True
vec_env_rng_align: False
env_num: ${task.env_runner.env_num}
with_pointcloud: True
encoder_output_dim: 64
only_bc: False
offline_use_aug: True
save_data: False
distill_phase: null # 'after_dp', 'after_offline', 'after_online'
update_phase: 'step' # 'step', 'iteration'
distill_loss_type: 'action_same_noise' # 'action' 'back_up'
distill2mean: False
data_collect: False
off2off: False
off2off_no_bc: False
use_recon: False
use_vib: False
dynamics_type: 'mlp'
predict_r: False
offline_cp_timestamp: null
offline_cp_timestep: null
crop_shape: ${task.crop_shape}
wo_dataset: False
# 添加encoder选择参数（移到全局）
encoder_type: "resnet"  # 可选: "resnet", "vit"
use_wandb: True
chunk_as_single_action: True
chunk_adv_clip: null
offline_chunk_ratio_mode: scalar
offline_chunk_adv_mode: scalar_iql
chunk_vdelta_gae_n_rollout: 3
chunk_vdelta_gae_lambda: 0.95
chunk_vdelta_gae_chunk_source: repeat_first
use_pre_norm: False
load_bc: False
gamma: 0.99
kl_annealing: True
bppo_chunk_level_ratio: True
lddm:
  _target_: rl_100.policy.lddm.LDDM
  shape_meta: ${shape_meta}
  scheduler_type: 'ddim' # 'cm', 'ddim', 'lddm'
  num_inference_steps: ${num_inference_steps}
  condition_type: film
  use_down_condition: true
  use_mid_condition: true
  use_up_condition: true
  policy_layer_norm: True
  model: 'skipnet' # dp3 sample_dp3 mlp
  act: 'relu' # relu, leaky_relu, mish
  point_downsample: true
  diffusion_step_embed_dim: 256
  mlp_policy_depth: 2
  n_action_steps: ${n_action_steps}
  chunk_as_single_action: ${chunk_as_single_action}
  down_dims:
  - 512
  - 1024 
  - 2048
  encoder_output_dim: 128
  kernel_size: 5
  n_groups: 8
  use_action_embed: ${use_action_embed}
  predict_r: ${predict_r}
  action_embed_dim: null
  action_embed_layer_norm: ${dynamics.action_embed_layer_norm}
  cm_noise_scheduler:
    _target_: rl_100.unidpg.diffusion_policy.diffusers_patch.lcm_scheduler.LCMSchedulerExtended #.ddim_with_logprob_dpok.DDIMScheduler
    num_train_timesteps: 10
    beta_start: 0.00085
    beta_end: 0.012
    beta_schedule: scaled_linear
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon
    original_inference_steps: ${num_inference_steps} # original_inference_steps cannot be larger than num_train_timesteps
    clip_std_min: ${clip_std_min}
    clip_std_max: ${clip_std_max}
  ddim_noise_scheduler:
    _target_: rl_100.unidpg.diffusion_policy.diffusers_patch.ddim_with_logprob_dpok.DDIMSchedulerExtended # diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 1
    prediction_type: sample
    clip_std_min: ${clip_std_min}
    clip_std_max: ${clip_std_max}
vrl3:
  env_feature_type: 'pixels'
  action_repeat: 2
  frame_stack: 1
  reward_rescale: true # TODO think about this...
  eval_episodes: 50
  save_video: true


policy:
  _target_: rl_100.policy.rl100_2d.RL1002D
  use_point_crop: true
  condition_type: film
  use_down_condition: true
  use_mid_condition: true
  use_up_condition: true
  joint_opt_encoder: False
  integrate_strategy: 'concat' # concat, sum
  model: 'sample_dp3' # dp3 sample_dp3 mlp
  feature_type: ${feature_type} # 2D, 3D, or 2D3D
  use_agent_pos: ${use_agent_pos}
  use_visual: True
  use_pretrained_2DEncoder: ${use_pretrained_2DEncoder}
  policy_layer_norm: True
  diffusion_step_embed_dim: 256
  encoder_hidden_dim: 256
  encoder_depth: 2
  mlp_policy_depth: 3
  stage1_model_name: 'resnet6_32channel'
  act: 'mish' # relu, leaky_relu, mish
  use_recon: ${use_recon}
  w_pc: False
  down_dims:
  - 256
  - 512
  - 1024
  crop_shape: ${task.crop_shape}
  encoder_output_dim: ${encoder_output_dim}
  horizon: ${horizon}
  kernel_size: 5
  n_action_steps: ${n_action_steps}
  chunk_as_single_action: ${chunk_as_single_action}
  vec_env_rng_align: ${vec_env_rng_align}
  n_groups: 8
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: ${num_inference_steps}
  scheduler_type: 'cm'
  img_shape: [3, 84, 84]
  use_layer_norm: True
  encoder_type: ${encoder_type}
  # cm_noise_scheduler:
  #   _target_: rl_100.unidpg.diffusion_policy.diffusers_patch.lcm_scheduler.LCMSchedulerExtended #.ddim_with_logprob_dpok.DDIMSchedulerExtended # diffusers.schedulers.scheduling_ddim.DDIMScheduler
  #   num_train_timesteps: 10
  #   beta_start: 0.0001
  #   beta_end: 0.02
  #   beta_schedule: squaredcos_cap_v2
  #   clip_sample: True
  #   set_alpha_to_one: True
  #   steps_offset: 0
  #   prediction_type: sample
  #   original_inference_steps: ${num_inference_steps} # original_inference_steps cannot be larger than num_train_timesteps
  cm_noise_scheduler:
    _target_: rl_100.unidpg.diffusion_policy.diffusers_patch.lcm_scheduler.LCMSchedulerExtended #.ddim_with_logprob_dpok.DDIMSchedulerExtended # diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 1
    prediction_type: sample
    original_inference_steps: ${num_inference_steps} # original_inference_steps cannot be larger than num_train_timesteps
    clip_std_min: ${clip_std_min}
    clip_std_max: ${clip_std_max}
    
  ddim_noise_scheduler:
    _target_: rl_100.unidpg.diffusion_policy.diffusers_patch.ddim_with_logprob_dpok.DDIMSchedulerExtended # diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 1
    prediction_type: epsilon
    clip_std_min: ${clip_std_min}
    clip_std_max: ${clip_std_max}

  use_cm: True
  cm_inference_steps: ${cm_inference_steps}
  ddim_inference_steps: ${num_inference_steps}

  # 根据encoder_type选择不同的obs_encoder配置
  obs_encoder: ${encoders.${encoder_type}}
  
  obs_as_global_cond: true
  shape_meta: ${shape_meta}

  use_pc_color: False
  pointnet_type: "pointnet"
  pointcloud_encoder_cfg:
    in_channels: 3
    out_channels: ${policy.encoder_output_dim}
    use_layernorm: true
    final_norm: layernorm # layernorm, none
    normal_channel: False

  use_aug: False

# 定义不同的编码器配置
encoders:
  resnet:
    _target_: rl_100.model.vision.multi_image_obs_encoder.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    use_agent_pos: ${use_agent_pos}
    resize_shape:
    - 224
    - 224
    crop_shape: ${task.crop_shape}
    random_crop: true
    rgb_model:
      _target_: rl_100.model.vision.model_getter.get_resnet
      name: resnet18
      weights: r3m
    use_group_norm: true
    share_rgb_model: false
    imagenet_norm: true
    use_recon: ${use_recon}
    use_vib: ${use_vib}
    recon_loss_weight: 0.05
    kl_loss_weight: 1.0
    kl_beta: 1e-4
    
  vit:
    _target_: rl_100.model.vision.encoder.EncoderMultiViewVisionTransformer
    shape_meta: ${shape_meta}
    use_agent_pos: ${use_agent_pos}
    resize_shape: null
    crop_shape: ${task.crop_shape}
    random_crop: true
    patch_size: 14
    embed_dim: 256
    depth: 4
    num_heads: 4
    decoder_embed_dim: 256
    decoder_depth: 3
    decoder_num_heads: 4
    mlp_ratio: 4.0
    conv_embed: false
    reward_pred: false
    latent_dim: 128
    pooling_method: "attention"
    attention_pool_heads: 1
    use_latent_projection: false
    loss_weight: 0.5
ema:
  _target_: rl_100.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False


val_dataloader:
  batch_size: 128
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True 
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 1600
  num_critic_epochs: 600
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 50
  checkpoint_every: 50
  val_every: 1
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0
  max_grad_norm: 1.0
  ema_decay: 0.95

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: ${training.seed}
  project: ${name}+${task_name}
  resume: False
  tags:
  - ft-dp3

checkpoint:
  save_ckpt: False # if True, save checkpoint every checkpoint_every
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True # this only saves when save_ckpt is True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${task.name}/${training.seed}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${task.name}/${training.seed}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${task.name}/${training.seed}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}

critic:
  q_hidden_dim: 512
  q_depth: 3
  q_lr: 1.0e-4
  target_update_freq: 2
  tau: 0.005
  gamma: ${gamma}
  v_hidden_dim: 512
  v_depth: 3
  v_lr: 1.0e-4
  omega: 0.7
  q_layer_norm: false
  action_embed_layer_norm: false
  action_scale_norm: false
  is_double_q: True
  is_iql: True
  is_share_encoder: true
  fix_encoder: true
  resume: True
  load_pretrain: True

unio4:
  bppo_steps: 8000
  bppo_lr: 1.0e-5
  clip_ratio: 0.25
  entropy_weight: 0.0
  decay: 0.96
  omega: 0.7
  is_clip_decay: true
  is_bppo_lr_decay: False
  is_update_old_policy: True
  is_linear_decay: True
  bppo_batch_size: 512
  temperature: null
  eval_step: 50
  eval_freq: 1000
  ratio_strategy: 'sum'
  top_k: 1
  fix_encoder: true
  rollout_length: 20
  use_gae: false
  first_action: false
  use_ema_eval: false
  idql_eval: False
  eval_times: 1
  final_reward: True
  finetune_batch_size: 128

dynamics:
  gamma: ${gamma}
  action_embed_layer_norm: false
  action_scale_norm: false
  tau: 0.005
  alpha: 0.1
  auto_alpha: True
  target_entropy: null
  alpha_lr: 3.0e-5
  deterministic_backup: True
  max_q_backup: True
  norm_reward: True
  num_q_ensemble: 10
  dynamics_lr: 3.0e-4 
  dynamics_max_epochs: 200
  max_epochs_since_update: 50
  dynamics_hidden_dims: [400, 400, 400, 400] #[1024, 1024, 512, 512] # 
  dynamics_weight_decay: [2.5e-5, 5.0e-5, 7.5e-5, 7.5e-5, 1.0e-4]
  n_ensemble: 7
  n_elites: 5
  rollout_freq: 1000
  rollout_batch_size: 50000
  rollout_length: 20
  penalty-coef: 1.0
  num_samples: 10
  model_retain_epochs: 5
  real_ratio: 0.05
  load_dynamics_path: null
  epoch: 200
  step_per_epoch: 1000
  eval_episodes: 10
  batch_size: 128
  lr_scheduler: False
  penalty_coef: 0.5
  predict_delta: True
  first_action: False
  fix_encoder: True
  tqdm_interval_sec: 1.0
  prediction_mode: "last" # "last" or "full"; for action chunking mode, if you use multi-step observation please set to "full"
  use_true_ensemble: True

ppo:
  env_name: ${task.name}
  seed: ${training.seed}
  max_train_steps: 1000000 # 1e6 in regular format
  evaluate_freq: 20000   # 5e3 in regular format
  save_freq: 20
  enable_ratio_logging: true
  ratio_log_every_updates: 10
  ratio_plot_on_final_flush: true
  batch_size: 2048
  mini_batch_size: 128
  gpu: ${training.device}
  path: null
  v_hidden_width: 512
  v_depth: 3
  lr_bc: 1.0e-4
  lr_a: 3.0e-6
  lr_c: 3.0e-4
  gamma: ${gamma}
  lamda: 0.95
  epsilon: 0.2
  K_epochs: 10
  use_adv_norm: true               # Trick 1: advantage normalization
  use_state_norm: true             # Trick 2: state normalization
  use_reward_norm: false           # Trick 3: reward normalization
  use_reward_scaling: true         # Trick 4: reward scaling (if use here, please retrain the value function)
  entropy_coef: 0.01               # Trick 5: policy entropy
  use_lr_decay: true               # Trick 6: learning rate Decay
  use_grad_clip: true              # Trick 7: Gradient clip
  use_orthogonal_init: true        # Trick 8: orthogonal initialization
  set_adam_eps: true               # Trick 9: set Adam epsilon=1e-5
  use_tanh: true                   # Trick 10: tanh activation function
  is_from_bppo: false
  is_load_value: false
  pi_load_path: pi_
  v_load_path: null
  r_scale: 1.0
  is_clip_value: true
  is_decay_pi: false
  tau: 0.005
  std_upper_bound: 0.0
  is_dp: true
  T: 5
  beta_schedule: vp
  is_timesteps: false
  num_inference_steps: ${num_inference_steps}
  ratio: 5
  ratio_strategy: sum
  top_k: 1
  iterations: 50
  update_distribution: false
  bc_in_loop: false
  update_strategy: model
  critic_strategy: iql
  eta: 1.0
  fix_encoder: False
  idql_eval: false
  use_bc: false
  share_encoder: false  
  capacity: 1000000
  iql_ft: false
  ft_q_lr: 1.0e-4
  ft_v_lr: 1.0e-4
  scale_strategy: null # number dynamic
  num_critic_epochs: 250
  encoder_lr_scale: 1.0
  actor_grad: true
  online_start_training:  1
  clip_std_decay: false
  adaptive_kl: 0.02
  min_lr_actor: 5.0e-7
  max_lr_actor: 1.0e-5
  min_lr_critic: 1.0e-4
  max_lr_critic: 1.0e-3
  iql_steps: 10
  idql_batch_size: 256
  iql_omega: 0.7
  fix_iql_encoder: True
  iql_use_policy_encoder_features: False
  iql_q_encoder: False
  iql_v_encoder: False
  v_encoder: False
  load_online_cp: False
  save_online_cp: False
  online_cp_save_freq: 2
  data_ratio: 0.7
  recon: False
  value_recon: False
  online_iql_recon: False
  iql_encoder_update_with: q
  is_share_iql_encoder: True
  idql_rollout: False
  force_stochastic_online: True
  per_step_recon: True
online_v:
  state_dim: null
  v_hidden_width: 256
  v_depth: 3
  lr: 1.0e-4
  device: ${training.device}
